### ISSUE TITLE
Failed to Process Update Information

### ISSUE THREAD

**Issue by miketheitguy** [Draconic-Inc/BrandonsCore#95]
`[11:49:45] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [brandonscore] Starting version check at https://version-check.covers1624.net/check/?mod=BrandonsCore&mc=1.16.5
[11:49:46] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
java.io.FileNotFoundException: https://version-check.covers1624.net/check/?mod=BrandonsCore&mc=1.16.5
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_311] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_311] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_311] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_311] {}
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source) ~[?:1.8.0_311] {}
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source) ~[?:1.8.0_311] {}
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_311] {}
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source) ~[?:1.8.0_311] {}
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_311] {}
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_311] {}
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_311] {}
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:171) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:187) ~[forge:?] {re:classloading}
	at java.lang.Iterable.forEach(Unknown Source) [?:1.8.0_311] {}
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:139) [forge:?] {re:classloading}
Caused by: java.io.FileNotFoundException: https://version-check.covers1624.net/check/?mod=BrandonsCore&mc=1.16.5
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_311] {}
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_311] {}
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:1.8.0_311] {}
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:1.8.0_311] {}
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:155) ~[forge:?] {re:classloading}
	... 3 more`

**Comment by FoxMcloud5655** [comment]
This is non-critical and has been put on the back burner for now.

**Comment by brandon3055** [comment]
This is related to the update checker which is not yet implemented.
